name: street_kind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  retrofit: ^4.0.3
  faker: ^2.1.0
  multiavatar: ^0.1.5
  flutter_svg: ^2.0.9
  collection: ^1.18.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_location_marker: ^8.0.4
  geolocator: ^10.1.0
  qr_code_dart_scan: ^0.7.4
  image_picker: ^1.0.7
  lottie: ^3.0.0
  icons_launcher: ^2.1.7
  google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.0.6
  flutter_gen_runner:
  slang_build_runner: ^3.29.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/raster/
    - assets/animations/

  fonts:
  - family: Cabin
    fonts:
      - asset: assets/fonts/Cabin/Cabin-Regular.ttf
      - asset: assets/fonts/Cabin/Cabin-Medium.ttf
        weight: 500
      - asset: assets/fonts/Cabin/Cabin-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Cabin/Cabin-Bold.ttf
        weight: 700

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true
